sudo: required
services:
  - docker

before_install:
  - docker build -t matipadocker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true matipadocker/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: docker-app
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-482306776553"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
